title = "imgen"

[owner]
name = "Istvan Szukacs <istvan@datadeft.eu>"
dob = 2021-04-07T14:55:22Z

[main]
log_pattern = '%(asctime)s %(levelname)-4s %(message)s'
log_folder = 'logs'
log_date_fmt = '%Y-%m-%d %H:%M:%S'

